name: Build and Publish Tawhiri Downloader Image
on:
  # workflow_dispatch allows the workflow to be triggered manually
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  build-and-publish-image:
    uses: ./.github/workflows/build-and-publish-image.yaml
    with:
      image-name: tawhiri-downloader
      image-dir: "."
    secrets: inherit
